#define CATCH_CONFIG_MAIN

#include "CharArray_Test.h"
#include "Random_Test.h"
#include "Singleton_Test.h"
#include "Timer_Test.h"
#include "Buffer_Test.h"
#include "Path_Test.h"
#include "Logger_Test.h"
#include "Serializing_Test.h"
#include "Json_Test.h"
#include "StringUtils_Test.h"
#include "VectorUtils_Test.h"
#include "ObjectData_Test.h"
#include "DynamicBuffer_Test.h"
#include "ReadStream_Test.h"
#include "WriteStream_Test.h"