# This workflow is used to set up Vcpkg and install packages.
name: "Common Setup"

on:
  workflow_call:
    inputs:
      vcpkg-json:
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  common-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore Vcpkg cache
        uses: actions/cache@v2
        with:
          path: vcpkg
          key: vcpkg-${{ runner.os }}-${{ inputs.vcpkg-json }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ inputs.vcpkg-json }}

      - name: Install Vcpkg
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git
            cd vcpkg
            ./bootstrap-vcpkg.sh
          fi
        working-directory: ${{ github.workspace }}

      - name: Install Vcpkg packages
        run: |
          cd vcpkg
          ./vcpkg install --feature-flags=manifests
        working-directory: ${{ github.workspace }}
